<a href="https://colab.research.google.com/github/shubh7185/DEEP_LEARNING/blob/main/fake_news.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd


In [38]:
df=pd.read_csv('/content/drive/MyDrive/deep learning/train.csv')

In [39]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [40]:
df=df.dropna()

In [41]:
x=df.drop('label',axis=1)

In [42]:
y=df['label']

In [43]:
x.shape
y.shape

(18285,)

In [44]:
import tensorflow as tf

In [45]:
tf.__version__

'2.12.0'

In [46]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.text import one_hot

In [48]:
voc_size=5000

In [49]:
messages=x.copy()

In [50]:
messages.reset_index(inplace=True)

In [51]:
import nltk
import re
from nltk.corpus import stopwords

In [52]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [53]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
  print(i)
  review=re.sub('[^a-zA-Z]',' ',messages['title'][i])
  review=review.lower()
  review=review.split()

  review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [54]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [55]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[4879, 4645, 3412, 4317, 670, 3962, 307, 4408, 2037, 3237],
 [3775, 4583, 4318, 872, 4050, 1476, 1017],
 [743, 2297, 1942, 3592],
 [2826, 3332, 2883, 2612, 1064, 5],
 [1046, 4050, 155, 60, 278, 4672, 4050, 3792, 3059, 791],
 [427,
  4798,
  19,
  1970,
  572,
  921,
  3363,
  3796,
  4715,
  2130,
  1003,
  3909,
  4782,
  2835,
  1017],
 [18, 2418, 2894, 43, 4595, 2032, 4620, 843, 3278, 11, 290],
 [3388, 2500, 3155, 1435, 286, 2609, 921, 1118, 3278, 11, 290],
 [798, 2505, 4792, 2992, 4192, 275, 1180, 1476, 921, 1749],
 [476, 3351, 883, 341, 2679, 1829, 1147, 401],
 [777, 1608, 4768, 1754, 935, 2322, 2500, 1191, 3976, 4043, 3555],
 [2612, 4079, 670, 275, 921, 286],
 [2093, 2101, 3023, 273, 3862, 3241, 4819, 129, 1416],
 [574, 1557, 1559, 2319, 153, 2082, 4055, 3278, 11, 290],
 [3234, 683, 437, 3271, 3902, 3278, 11, 290],
 [3215, 4862, 2941, 3803, 4781, 3057, 4942, 3260, 3051, 4916],
 [4857, 2270, 4583],
 [329, 1204, 1147, 3538, 921, 1102, 4619, 1017],
 [3037, 2338, 4318, 4620, 4942, 2

In [56]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 4408 2037 3237]
 [   0    0    0 ... 4050 1476 1017]
 [   0    0    0 ... 2297 1942 3592]
 ...
 [   0    0    0 ... 3278   11  290]
 [   0    0    0 ... 4198 4409 3258]
 [   0    0    0 ... 2247 4227 4667]]


In [57]:
# creating model
embedding_vectors_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vectors_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_3 (LSTM)               (None, 100)               56400     
                                                                 
 dense_3 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [58]:
import numpy as np
x_final=np.array(embedded_docs)
y_final=np.array(y)

In [59]:
x_final.shape

(18285, 20)

In [60]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_final,y_final,test_size=0.3,random_state=42)


In [61]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
200/200 [==============================] - 14s 55ms/step - loss: 0.3278 - accuracy: 0.8547 - val_loss: 0.2015 - val_accuracy: 0.9158
Epoch 2/10
200/200 [==============================] - 8s 41ms/step - loss: 0.1361 - accuracy: 0.9473 - val_loss: 0.2164 - val_accuracy: 0.9194
Epoch 3/10
200/200 [==============================] - 11s 54ms/step - loss: 0.0968 - accuracy: 0.9651 - val_loss: 0.2205 - val_accuracy: 0.9200
Epoch 4/10
200/200 [==============================] - 11s 53ms/step - loss: 0.0691 - accuracy: 0.9765 - val_loss: 0.2394 - val_accuracy: 0.9092
Epoch 5/10
200/200 [==============================] - 9s 43ms/step - loss: 0.0484 - accuracy: 0.9844 - val_loss: 0.3302 - val_accuracy: 0.9165
Epoch 6/10
200/200 [==============================] - 11s 54ms/step - loss: 0.0330 - accuracy: 0.9891 - val_loss: 0.3116 - val_accuracy: 0.9134
Epoch 7/10
200/200 [==============================] - 12s 61ms/step - loss: 0.0213 - accuracy: 0.9945 - val_loss: 0.3783 - val_accuracy: 0

In [62]:
# The threshold in binary classification is a crucial parameter that determines
# how predicted probabilities are translated into class labels
# . It defines the boundary between considering a sample as belonging to the positive
# class or the negative class. When the predicted probability for a sample exceeds
# the threshold, it's classified as the positive class; otherwise, it's classified
# as the negative class.

import numpy as np
from sklearn.metrics import confusion_matrix

# Assuming 'model' is your trained Sequential model
y_pred_prob = model.predict(x_test)

# Threshold the predicted probabilities to get binary class predictions
threshold = 0.5  # You can adjust this threshold as needed
y_pred_binary = (y_pred_prob >= threshold).astype(int)

# Compute the confusion matrix
cm = confusion_matrix(y_test, y_pred_binary)

print(cm)



172/172 [==============================] - 2s 7ms/step
[[2830  277]
 [ 201 2178]]


In [63]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred_binary)

0.912869121399927

In [64]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_binary))

              precision    recall  f1-score   support

           0       0.93      0.91      0.92      3107
           1       0.89      0.92      0.90      2379

    accuracy                           0.91      5486
   macro avg       0.91      0.91      0.91      5486
weighted avg       0.91      0.91      0.91      5486

