<a href="https://colab.research.google.com/github/shubh7185/DEEP_LEARNING/blob/main/wordembedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good developer',
      'understand the meaning of words',
      'your words are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good developer',
 'understand the meaning of words',
 'your words are good']

In [8]:
voc_size=10000

one hot representation

In [9]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
print(one_hot_repr)

[[5261, 4400, 9223, 3569], [5261, 4400, 9223, 6231], [5261, 2885, 9223, 9548], [9064, 1460, 3784, 3621, 3007], [798, 5261, 1840, 9223, 6688], [4851, 6688, 8234, 3621]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5261 4400 9223 3569]
 [   0    0    0    0 5261 4400 9223 6231]
 [   0    0    0    0 5261 2885 9223 9548]
 [   0    0    0 9064 1460 3784 3621 3007]
 [   0    0    0  798 5261 1840 9223 6688]
 [   0    0    0    0 4851 6688 8234 3621]]


In [13]:
dim=15

In [14]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 139ms/step
[[[-0.04197783  0.01808948 -0.03703076  0.01175483 -0.00786038
    0.02454715  0.04287219  0.02624729 -0.02445026 -0.0370485 ]
  [-0.04197783  0.01808948 -0.03703076  0.01175483 -0.00786038
    0.02454715  0.04287219  0.02624729 -0.02445026 -0.0370485 ]
  [-0.04197783  0.01808948 -0.03703076  0.01175483 -0.00786038
    0.02454715  0.04287219  0.02624729 -0.02445026 -0.0370485 ]
  [-0.04197783  0.01808948 -0.03703076  0.01175483 -0.00786038
    0.02454715  0.04287219  0.02624729 -0.02445026 -0.0370485 ]
  [ 0.0417467  -0.03314737  0.01715562 -0.04533768  0.00285041
   -0.01580349 -0.04403181 -0.00012429  0.01940003  0.02314341]
  [ 0.00771702 -0.03448994  0.01339438  0.04063429 -0.00435541
    0.01868976 -0.00377098 -0.04462441  0.03228767 -0.04437612]
  [ 0.01041992 -0.04387436 -0.02361498 -0.02391719 -0.01718773
   -0.01087958 -0.01212244 -0.00653887  0.00229094 -0.04527983]
  [ 0.00234574  0.03725373  0.00108322 -0.00192546 -0.0181